<?php $this->page_title = 'Rob\'s Blog &raquo; ' . 'About'; ?>
<h3>The Site</h3>
<p>
I've parked this area on the world wide web as a spot where I can both share things that I've learned, and also experiment with technologies that I'm interested in; namely web development related. To watch the code behind the site grow, and to see how I've implemented some things, check out what's <a title="behind the site" href="http://github.com/rkeplin/Blog">behind the site</a>.
</p> 

<h3>The Author</h3>
<p>
In September, 2005 I began my quest for a degree in Computer Science at <a href="http://www.rivier.edu">Rivier College</a>. It was there, where I had wrote my very first program.  Of course, it was a simple <i>Hello World</i> script.  Written in Java, and compiled with <a href="http://www.bluej.org/">BlueJ</a>.
</p>

<p>In the Summer of 2007, I was fortunate enough to get a summer internship as a Java Developer with <a href="http://www.kewill.com/">Kewill</a>. That experience was nothing short of mind-opening. I quickly realized that the more I knew about computers, the more I <i>didn't</i> know.
</p>

<p>
 During the Summer of 2008, I was able to work with <a href="http://www.acorncreative.com">Acorn Creative</a> as a PHP Developer. It seemed as though developing for the web was speedier than for the desktop, which influenced me to learn more about web development.
</p>

<p>
   I graduated from school in May, 2009, and found a nice fit as a Web Developer with <a href="http://www.acsacc.com">Administrative Claim Service, Inc.</a> I have been happily employed there, since.
</p>