<?php $this->page_title = 'Rob\'s Blog'; ?>

<div class="post">
    <h1><?= $this->post->title ?></h1>
    <div class="post-details">
        <a title="<?= $this->post->category->name ?>" href="/blog/category/<?= urlencode($this->post->category->name) ?>/"><?= $this->post->category->name ?></a> | Posted by: <?= $this->post->user->name ?> on <?= date("F jS, Y", strtotime($this->post->date_added)) ?>
    </div>
    <div class="post-content">
        <?= stripslashes($this->post->content) ?>
    </div>

    <p><img alt="comment" src="/public/images/comment_blue.gif" /><a title="Make a comment" href="/blog/view/<?= $this->post->category->name ?>/<?= $this->post->title ?>/#parent_id-label">Leave a comment</a></p>
</div>

<div class="sponsors">
    	<p>Interests:</p>
    	<ul>
    		<li>Discover how <a title="jango mail" href="http://jangomail.com">email marketing</a> will help your site grow.</li>
    	</ul>
    </div>