<?php if ($this->pageCount > 1): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous, 'search' => $this->search)); ?>">
    &laquo; Previous
  </a> |
<?php else: ?>
  <span class="disabled">&laquo; Previous</span> |
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page, 'search' => $this->search)); ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next, 'search' => $this->search)); ?>">
    Next &raquo;
  </a>
<?php else: ?>
  <span class="disabled">Next &raquo;</span>
<?php endif; ?>
</div>
<?php endif; ?>