<div class="post">
    <h1>Edit Post (<a href="/blog/view/category/<?= urlencode($this->form->category_id->getMultiOption($this->form->category_id->getValue())) ?>/title/<?= urlencode($this->form->title->getValue()); ?>">view blog</a></a>)</h1>
    <?php if(isset($this->message)) : ?>
    <div class="message">
        <?= $this->message; ?>
    </div>
    <?php endif; ?>
    
    <?= $this->form ?>
</div>