<?php $this->page_title = 'Rob\'s Blog &raquo; ' . 'Archives' . ' &raquo; ' . $this->year; ?>

<div class="post">
    <h1>Archives from year <?= $this->year ?></h1>
    <?php if(count($this->posts) > 0) : ?>
    <ul class="latest-blogs">
    <?php foreach($this->posts as $post) : ?>
        <li><a title="<?= $post->title ?>" href="/blog/view/<?= $post->category->name ?>/<?= $post->title ?>/"><?= $post->title ?></a></li>
    <?php endforeach; ?>
    </ul>
    
    <?= $this->paginationControl($this->posts, 'Sliding', 'pagination.phtml'); ?>
    
    <?php else : ?>
        There have been no posts in the year <strong><?= $this->year ?></strong>.
    <?php endif; ?>
</div>